### PR TITLE
Fix duplicate LLVM linking for shared library users

### LINKED ISSUE #134: bug:  Fix LLVM symbol visibility and linking for proteus
if you 
(1) build proteus statically 
(2) link to RAJAPerf
(3) run `raja-perf.exe`

you will get the dreaded
`: CommandLine Error: Option 'o' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
zsh: abort (core dumped)  ./bin/raja-perf.exe`

This can be resolved in a couple of ways, one of which is to limit the symbol visibility of LLVM symbols from libproteus with a symbol map like
`{
local:
    *LLVM*
}`

### PR DESCRIPTION
**Pull request by ggeorgakoudis**
- Propagate dependency to proteus when building a shared library

Closes #134

### CODE REVIEW

**Comment by tbennun** [comment]
LGTM, double checking against my test

File: tests/integration/hip/cmake-shared_lib_and_executable-static_proteus/main.cpp [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+// RUN: ./daxpy.%ext | FileCheck %s --check-prefixes=CHECK,CHECK-SECOND
+#include <cstddef>
+#include <cstdlib>
+#include <iostream>
+
+#include "../../../gpu/gpu_common.h"
+
+void daxpy(double a, double *x, double *y, int N);
+
+
```
Comment (tbennun) [inline tests/integration/hip/cmake-shared_lib_and_executable-static_proteus/main.cpp:12]:
```suggestion

```

**Review by tbennun — APPROVED** [review]

**Comment by tbennun** [comment]
@ggeorgakoudis LGTM
